name: earth-github-action-test CI

# 하기 내용에 해당하는 이벤트 발생 시 github action 동작
on:
    push: # feature/*와 develop 브랜치에서 push가 일어났을 때 github action 동작
        branches:
            - 'feature/*'
            - 'develop'
            - 'main'
            - 'origin'
    pull_request: # feature/*와 develop 브랜치에서 PR이 일어났을 때 github action 동작
        branches:
            - 'feature/*'
            - 'develop'
            - 'main'
            - 'origin'

# 참고사항
# push가 일어난 브랜치에 PR이 존재하면, push에 대한 이벤트와 PR에 대한 이벤트 모두 발생합니다.

# workflow 정의
jobs:
    build:
        runs-on: ubuntu-latest # 실행 환경 지정 / 우분투 실행환경 사용

        steps:
            # step 1
            - name: Checkout source code
              uses: actions/checkout@v2 # github action 버전 지정(major version)

            # step 2
            - name: Set up JDK 1.8 # JAVA 버전 지정
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            # step 3
            - name: Grant execute permission for gradlew
              run: chmod +x ./gradlew # gradlew 명령어를 사용하기 위한 권한 설정

            # step 4
            - name: Build with Gradle # 실제 application build(-x 옵션을 통해 test는 제외)
              run: ./gradlew build -x test

            # step 5
            - name: Test with Gradle # test application build
              run: ./gradlew test

            # step 6
            - name: Publish Unit Test Results # test 후 result를 보기 위해 추가
              uses: EnricoMi/publish-unit-test-result-action@v1
              if: ${{ always() }} # test가 실패해도 report를 남기기 위해 설정
              with:
                  files: build/test-results/**/*.xml
